# Generated by Django 4.0.3 on 2022-03-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='defult/index.png', null=True, upload_to='profile_user'),
        ),
    ]
