# Generated by Django 4.0.3 on 2022-03-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount', '0004_profile_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='defult/index.png', upload_to='profile_user'),
        ),
    ]
