# Generated by Django 3.2.8 on 2022-03-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blog_admin',
            field=models.BooleanField(default=False),
        ),
    ]
