# Generated by Django 4.0.3 on 2022-03-18 00:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create',
            field=models.DateField(default=datetime.datetime(2022, 3, 18, 0, 33, 54, 28366, tzinfo=utc)),
        ),
    ]
