# Generated by Django 4.0.3 on 2022-03-19 22:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_options_alter_article_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create',
            field=models.DateField(default=datetime.datetime(2022, 3, 19, 22, 26, 51, 985107, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='categorical',
            name='titel',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
