# Generated by Django 4.0.3 on 2022-03-20 01:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_create_alter_categorical_titel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.AlterField(
            model_name='article',
            name='create',
            field=models.DateField(default=datetime.datetime(2022, 3, 20, 1, 37, 15, 27449, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='categorical',
            name='titel',
            field=models.CharField(max_length=20),
        ),
    ]
