# Generated by Django 4.0.3 on 2022-03-20 01:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_article_slug_alter_article_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create',
            field=models.DateField(default=datetime.datetime(2022, 3, 20, 1, 49, 47, 78256, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to='blog/image'),
        ),
    ]
