# Generated by Django 4.0.3 on 2022-03-20 01:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_article_create_alter_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categori',
        ),
        migrations.AlterField(
            model_name='article',
            name='create',
            field=models.DateField(default=datetime.datetime(2022, 3, 20, 1, 57, 42, 267715, tzinfo=utc)),
        ),
    ]
