# Generated by Django 4.0.3 on 2022-03-20 02:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_article_categori_alter_article_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create',
            field=models.DateField(default=datetime.datetime(2022, 3, 20, 2, 58, 12, 87064, tzinfo=utc)),
        ),
    ]
